/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conexion.AccionesAsegurados;
import Conexion.BuscarAsegurados;
import Datos.ListaAsegurados;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Asegurados extends javax.swing.JPanel {

    /**
     * Creates new form Asegurados
     */
    
    public Asegurados() {
        initComponents();
        llenarTabla();
    }
    
    private void llenarTabla (){
        DefaultTableModel asegurados = new DefaultTableModel();
        asegurados.addColumn("Nombre");
        asegurados.addColumn("DNI");
        asegurados.addColumn("Teléfono");
        TBLasegurados.setModel(asegurados);
        Long DNI = (long)100000001;
        String nombre = "";
        if(!TXTnombreODNI.getText().trim().equals("")){
            boolean letra=true;
            for(int i = 0;i<TXTnombreODNI.getText().length();i++){
                char c = TXTnombreODNI.getText().charAt(i);
                if((c<'a' || c>'z') && (c<'A' || c>'Z' ) && (c<' ' || c>' '))letra=false;
            }
            if(letra==false){
                DNI = Long.parseLong(TXTnombreODNI.getText());
                nombre = "";
            }
            else{
                nombre = TXTnombreODNI.getText();
            }
        }
        BuscarAsegurados lista = new BuscarAsegurados(nombre, DNI);
        lista.execute();
        ListaAsegurados listAseg = lista.getListAseg();
        for (int i=0;i<listAseg.getSize();i++){
            Object [] o = null;            
            asegurados.addRow(o);
            asegurados.setValueAt(listAseg.getAsegurado(i).getNombreasegurado(),i, 0);
            asegurados.setValueAt(listAseg.getAsegurado(i).getDNInumero(), i, 1);
            asegurados.setValueAt(listAseg.getAsegurado(i).getTele1(), i, 2);
        }
        System.out.println("llene tabla "+ new SimpleDateFormat("HH:mm:ss").format(new Date().getTime()));
        System.out.println("--------------------------------------------------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTnombreODNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLasegurados = new javax.swing.JTable();
        BTNbuscar = new javax.swing.JButton();
        BTNnuevoasegurado = new javax.swing.JButton();

        jLabel1.setText("INGRESE NOMBRE O DNI:");
        jLabel1.setAlignmentY(0.0F);

        TXTnombreODNI.setToolTipText("");
        TXTnombreODNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombreODNIActionPerformed(evt);
            }
        });

        TBLasegurados.setAutoCreateRowSorter(true);
        TBLasegurados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "TEL", "DNI"
            }
        ));
        TBLasegurados.getTableHeader().setReorderingAllowed(false);
        TBLasegurados.setDefaultEditor(Object.class, null);
        TBLasegurados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLaseguradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLasegurados);

        BTNbuscar.setText("BUSCAR");
        BTNbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarActionPerformed(evt);
            }
        });

        BTNnuevoasegurado.setText("Crear");
        BTNnuevoasegurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnuevoaseguradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTnombreODNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BTNnuevoasegurado))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombreODNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(BTNbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNnuevoasegurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarActionPerformed
        llenarTabla();
    }//GEN-LAST:event_BTNbuscarActionPerformed

    private void TXTnombreODNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombreODNIActionPerformed
        llenarTabla();
    }//GEN-LAST:event_TXTnombreODNIActionPerformed

    private void BTNnuevoaseguradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnuevoaseguradoActionPerformed
        NuevoAsegurado nuevo = new NuevoAsegurado();
        nuevo.setVisible(true);
    }//GEN-LAST:event_BTNnuevoaseguradoActionPerformed

    private void TBLaseguradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLaseguradosMouseClicked
        if(evt.getClickCount() == 2){
            System.out.println("dobleclick");
        }
    }//GEN-LAST:event_TBLaseguradosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNbuscar;
    private javax.swing.JButton BTNnuevoasegurado;
    private javax.swing.JTable TBLasegurados;
    private javax.swing.JTextField TXTnombreODNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
