/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conexion.AccionesAsegurados;
import Datos.ListaAsegurados;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Asegurados extends javax.swing.JPanel {

    /**
     * Creates new form Asegurados
     */
    public Asegurados() {
        initComponents();
        llenarTabla();
    }
    
    private void llenarTabla (){
        DefaultTableModel asegurados = new DefaultTableModel();
        asegurados.addColumn("Nombre");
        asegurados.addColumn("DNI");
        asegurados.addColumn("Teléfono");
        TBLasegurados.setModel(asegurados);
        int DNI = 0;
        String nombre = "";
        if(!TXTnombreODNI.getText().trim().equals("")){
            char c = TXTnombreODNI.getText().charAt(0);
            if((c<'a' || c>'z') && (c<'A' || c>'Z' ) && (c<' ' || c>' ')){
                DNI = Integer.parseInt(TXTnombreODNI.getText());
            }
            nombre = TXTnombreODNI.getText();
        }
        ListaAsegurados listAseg = AccionesAsegurados.buscarAsegurados(nombre, DNI);
        for (int i=0;i<listAseg.getSize();i++){
            Object [] o = null;            
            asegurados.addRow(o);
            asegurados.setValueAt(listAseg.getAsegurado(i).getNombreasegurado(),i, 0);
            asegurados.setValueAt(listAseg.getAsegurado(i).getDNInumero(), i, 1);
            asegurados.setValueAt(listAseg.getAsegurado(i).getTele1(), i, 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTnombreODNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLasegurados = new javax.swing.JTable();

        jLabel1.setText("INGRESE NOMBRE O DNI:");
        jLabel1.setAlignmentY(0.0F);

        TXTnombreODNI.setToolTipText("");

        TBLasegurados.setAutoCreateRowSorter(true);
        TBLasegurados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "TEL", "DNI"
            }
        ));
        TBLasegurados.getTableHeader().setReorderingAllowed(false);
        TBLasegurados.setDefaultEditor(Object.class, null);
        jScrollPane1.setViewportView(TBLasegurados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTnombreODNI)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombreODNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLasegurados;
    private javax.swing.JTextField TXTnombreODNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
