/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author edudec
 */
public class INGautos extends javax.swing.JPanel {

    /**
     * Creates new form INGautos
     */
    public INGautos() {
        initComponents();
        BTNcargaotro.setVisible(false);
        BTNfinalizacarga.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CHKflota = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        TXTpatente = new TextField.CustomTextField();
        jLabel3 = new javax.swing.JLabel();
        customTextField1 = new TextField.CustomTextField();
        jLabel4 = new javax.swing.JLabel();
        customTextField2 = new TextField.CustomTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTaccesorios = new TextField.CustomTextField();
        BTNcargaotro = new javax.swing.JButton();
        BTNfinalizacarga = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CMBmarca = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CMBmodelo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TXTanio = new TextField.CustomTextField();

        jLabel1.setText("Flota:");

        CHKflota.setText("jCheckBox1");
        CHKflota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CHKflotaItemStateChanged(evt);
            }
        });
        CHKflota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHKflotaActionPerformed(evt);
            }
        });

        jLabel2.setText("Patente:");

        TXTpatente.setLargo(7);
        TXTpatente.setTexto(TextField.CustomTextField.Texto.LETRAMAYUSCULA);

        jLabel3.setText("Motor:");

        customTextField1.setLargo(25);
        customTextField1.setTexto(TextField.CustomTextField.Texto.LETRAMAYUSCULA);

        jLabel4.setText("Chasis:");

        customTextField2.setLargo(25);
        customTextField2.setTexto(TextField.CustomTextField.Texto.LETRAMAYUSCULA);

        jLabel5.setText("Accesorios: ");

        TXTaccesorios.setLargo(45);
        TXTaccesorios.setTexto(TextField.CustomTextField.Texto.LETRAMAYUSCULA);

        BTNcargaotro.setText("Carga otro");

        BTNfinalizacarga.setText("Finaliza carga");

        jLabel6.setText("Marca:");

        CMBmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Modelo:");

        CMBmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Año:");

        TXTanio.setLargo(4);
        TXTanio.setTexto(TextField.CustomTextField.Texto.SOLONUMERO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNcargaotro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNfinalizacarga))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTaccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTpatente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(customTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CHKflota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(CMBmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CMBmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTanio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CHKflota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMBmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CMBmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(TXTanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTpatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(customTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TXTaccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNcargaotro)
                    .addComponent(BTNfinalizacarga))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CHKflotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHKflotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHKflotaActionPerformed

    private void CHKflotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CHKflotaItemStateChanged
        if (CHKflota.isSelected()) {
            BTNcargaotro.setVisible(true);
            BTNfinalizacarga.setVisible(true);
        } else {
            BTNcargaotro.setVisible(false);
            BTNfinalizacarga.setVisible(false);
        }
    }//GEN-LAST:event_CHKflotaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcargaotro;
    private javax.swing.JButton BTNfinalizacarga;
    private javax.swing.JCheckBox CHKflota;
    private javax.swing.JComboBox<String> CMBmarca;
    private javax.swing.JComboBox<String> CMBmodelo;
    private TextField.CustomTextField TXTaccesorios;
    private TextField.CustomTextField TXTanio;
    private TextField.CustomTextField TXTpatente;
    private TextField.CustomTextField customTextField1;
    private TextField.CustomTextField customTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
