/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conexion.AccionesAsegurados;
import Conexion.AccionesUsuarios;
import Datos.DNITipo;
import Datos.ListaUsuarios;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author admin
 */
public class NuevoAsegurado extends javax.swing.JFrame {

    /**
     * Creates new form NuevoAegurado
     */
    
    public NuevoAsegurado() {
        initComponents();
        llenarComboDNI();
        llenarComboCobrador();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cancelar();
            }
        });
    }

    private void llenarComboDNI(){
        DNITipo dni = new DNITipo();
        ArrayList <String> DNI = dni.getDNItipo();
        for (String string : DNI) {
            CMBdnitipo.addItem(string);
        }
    }
    
    private void llenarComboCobrador (){
        ListaUsuarios usu = AccionesUsuarios.BuscaUsuario(0, "");
        for (int i=0;i<usu.getSize();i++){
            CMBcobrador.addItem(usu.getUsuario(i).getIdusuario()+" "+ usu.getUsuario(i).getNombre());
        }
    }
    
    private void cancelar (){
        int decision = javax.swing.JOptionPane.showConfirmDialog(this, "Desea cancelar la carga?","Cancelar",javax.swing.JOptionPane.OK_CANCEL_OPTION);
        if (decision == 0){
            System.out.println("0");
            this.dispose();
        }
    }
    
    private void agregaAsegurado(){
        Datos.Asegurados aseg = new Datos.Asegurados();
        aseg.setActividad(TXTactividad.getText().toUpperCase());
        aseg.setAlta(new java.sql.Date(new Date().getTime()));
        aseg.setCobrador(Integer.parseInt(CMBcobrador.getSelectedItem().toString().substring(0, 1).trim().toUpperCase()));
        aseg.setCodigopostal(TXTcodigopostal.getText().toUpperCase());
        aseg.setCuil(Long.parseLong(TXTcuil.getText().toUpperCase()));
        aseg.setDNItipo(CMBdnitipo.getSelectedItem().toString().substring(2,3).toUpperCase());
        aseg.setDNInumero(Integer.parseInt(TXTdninumero.getText().toUpperCase()));
        aseg.setDomicilioasegurado(TXTdomicilio.getText().toUpperCase());
        aseg.setDomiciliocobroasegurado(TXTdomiciliocobro.getText().toUpperCase());
        String activo = "I";
        aseg.setTele2(TXTtelefono2.getText());
        aseg.setTele1(TXTtelefono1.getText());
        aseg.setTele3(TXTtelefono3.getText());
        if (CHBactivo.isSelected())activo="A";
        aseg.setEstado(activo);
        aseg.setFechanac(new java.sql.Date(DATnacimiento.getDate().getTime()));
        aseg.setLocalidad(TXTlocalidad.getText().toUpperCase());
        aseg.setMail(TXTmail.getText().toUpperCase());
        aseg.setNombreasegurado(TXTnombre.getText().toUpperCase()+" "+TXTapellido.getText().toUpperCase());
        aseg.setObservaciones(TXTobservaciones.getText().toUpperCase());
        int resultado = AccionesAsegurados.insertaAsegurado(aseg);
        switch (resultado){
            case 0:javax.swing.JOptionPane.showMessageDialog(this, "Algo salio mal!","Error!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            case 1:javax.swing.JOptionPane.showMessageDialog(this, "El nuevo registro ha sido grabado","Registro Exitoso",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            case 2:javax.swing.JOptionPane.showMessageDialog(this, "Este DNI ya se encuentra registrado!","Dato Duplicado!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTtelefono3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TXTnombre = new javax.swing.JTextField();
        TXTapellido = new javax.swing.JTextField();
        DATnacimiento = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTcuil = new javax.swing.JTextField();
        TXTdomicilio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTactividad = new javax.swing.JTextField();
        TXTdomiciliocobro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TXTmail = new javax.swing.JTextField();
        TXTlocalidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTcodigopostal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CMBdnitipo = new javax.swing.JComboBox<>();
        CHBactivo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TXTtelefono1 = new javax.swing.JTextField();
        CMBcobrador = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TXTtelefono2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTobservaciones = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TXTdninumero = new javax.swing.JTextField();
        BTNguardar = new javax.swing.JButton();
        BTNcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        TXTtelefono3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTtelefono3KeyTyped(evt);
            }
        });

        jLabel11.setText("Fecha Nac.");

        jLabel1.setText("Nombre");

        DATnacimiento.setDateFormatString("d MMM, YYYY");
        DATnacimiento.setDoubleBuffered(false);
        DATnacimiento.setRequestFocusEnabled(false);

        jLabel2.setText("Apellido");

        jLabel12.setText("C.U.I.L.");

        jLabel3.setText("Domicilio");

        jLabel13.setText("Actividad");

        jLabel4.setText("Domicilio cobro");

        jLabel5.setText("Localidad");

        jLabel14.setText("Mail");

        jLabel15.setText("Estado");

        jLabel6.setText("C.P.");

        TXTcodigopostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTcodigopostalKeyTyped(evt);
            }
        });

        jLabel7.setText("DNI Tipo");

        CMBdnitipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));

        CHBactivo.setSelected(true);
        CHBactivo.setText("Activo");

        jLabel8.setText("Teléfono1");

        jLabel16.setText("Cobrador");

        TXTtelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTtelefono1KeyTyped(evt);
            }
        });

        CMBcobrador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sleccionar..." }));

        jLabel9.setText("Teléfono2");

        TXTtelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTtelefono2KeyTyped(evt);
            }
        });

        jLabel10.setText("Telefono3");

        TXTobservaciones.setColumns(20);
        TXTobservaciones.setLineWrap(true);
        TXTobservaciones.setRows(5);
        jScrollPane1.setViewportView(TXTobservaciones);

        jLabel17.setText("Observaciones");

        jLabel18.setText("DNI Número");

        TXTdninumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTdninumeroKeyTyped(evt);
            }
        });

        BTNguardar.setText("Guardar");
        BTNguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarActionPerformed(evt);
            }
        });

        BTNcancelar.setText("Cancelar");
        BTNcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CHBactivo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTcuil, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTtelefono3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTtelefono1)
                                    .addComponent(TXTmail)
                                    .addComponent(TXTnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTdomicilio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTlocalidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CMBdnitipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DATnacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXTapellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTactividad)
                                    .addComponent(CMBcobrador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TXTtelefono2)
                                    .addComponent(TXTdomiciliocobro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTcodigopostal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXTdninumero, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(BTNguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNcancelar)
                .addGap(0, 263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTlocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CMBdnitipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TXTtelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TXTtelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TXTcuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TXTmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTdomiciliocobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTcodigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(TXTdninumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTtelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DATnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TXTactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CMBcobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CHBactivo))
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNcancelar)
                    .addComponent(BTNguardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_BTNcancelarActionPerformed

    private void BTNguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarActionPerformed
        agregaAsegurado();
    }//GEN-LAST:event_BTNguardarActionPerformed

    private void TXTcodigopostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcodigopostalKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_TXTcodigopostalKeyTyped

    private void TXTdninumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdninumeroKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))evt.consume();
    }//GEN-LAST:event_TXTdninumeroKeyTyped

    private void TXTtelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefono1KeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))evt.consume();
    }//GEN-LAST:event_TXTtelefono1KeyTyped

    private void TXTtelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefono2KeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))evt.consume();
    }//GEN-LAST:event_TXTtelefono2KeyTyped

    private void TXTtelefono3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefono3KeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))evt.consume();
    }//GEN-LAST:event_TXTtelefono3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OSX".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAsegurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoAsegurado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcancelar;
    private javax.swing.JButton BTNguardar;
    private javax.swing.JCheckBox CHBactivo;
    private javax.swing.JComboBox<String> CMBcobrador;
    private javax.swing.JComboBox<String> CMBdnitipo;
    private com.toedter.calendar.JDateChooser DATnacimiento;
    private javax.swing.JTextField TXTactividad;
    private javax.swing.JTextField TXTapellido;
    private javax.swing.JTextField TXTcodigopostal;
    private javax.swing.JTextField TXTcuil;
    private javax.swing.JTextField TXTdninumero;
    private javax.swing.JTextField TXTdomicilio;
    private javax.swing.JTextField TXTdomiciliocobro;
    private javax.swing.JTextField TXTlocalidad;
    private javax.swing.JTextField TXTmail;
    private javax.swing.JTextField TXTnombre;
    private javax.swing.JTextArea TXTobservaciones;
    private javax.swing.JTextField TXTtelefono1;
    private javax.swing.JTextField TXTtelefono2;
    private javax.swing.JTextField TXTtelefono3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
